In [38]:

import torch
import numpy as np
import os

## from torchvision import datasets
## from torchvision import transforms
## import matplotlib.pyplot as plt
## from PIL import Image

import torch.optim as optim 
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader

from torchmetrics.functional.pairwise import pairwise_euclidean_distance



## AutoEncoder


In [39]:

privacy_tensor   = torch.randn( 1000, 784 )


In [40]:

x_train = privacy_tensor[:, :]
y_train = privacy_tensor[:, :]


In [41]:

train_ds = TensorDataset(x_train, y_train)
train_dl = DataLoader(dataset=train_ds, batch_size=64, shuffle=True)


In [42]:

class Autoencoder(nn.Module):
    
    def __init__(self, input_dim, encoding_dim):
        super(Autoencoder, self).__init__()
        
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, encoding_dim),
            nn.ReLU()
        )
        
        self.decoder = nn.Sequential(
            nn.Linear(encoding_dim, input_dim),
            nn.Sigmoid()  # For image data, use Sigmoid to limir output between 0 and 1
        )

    def forward(self, x):
        
        encoded = self.encoder(x)
        decoded = self.decoder(encoded)
        
        return decoded



In [43]:


input_dim    = 784  
encoding_dim = 32 

model     = Autoencoder(input_dim, encoding_dim)

optimizer = optim.Adam(model.parameters())
criterion = nn.MSELoss()


for epoch in range(10):
    for x,y in train_dl:
        optimizer.zero_grad()
        output = model( x)
        loss = criterion(output, y)
        loss.backward()
        optimizer.step()
        print(loss)


tensor(1.2505, grad_fn=<MseLossBackward0>)
tensor(1.2485, grad_fn=<MseLossBackward0>)
tensor(1.2458, grad_fn=<MseLossBackward0>)
tensor(1.2527, grad_fn=<MseLossBackward0>)
tensor(1.2451, grad_fn=<MseLossBackward0>)
tensor(1.2389, grad_fn=<MseLossBackward0>)
tensor(1.2303, grad_fn=<MseLossBackward0>)
tensor(1.2382, grad_fn=<MseLossBackward0>)
tensor(1.2270, grad_fn=<MseLossBackward0>)
tensor(1.2390, grad_fn=<MseLossBackward0>)
tensor(1.2361, grad_fn=<MseLossBackward0>)
tensor(1.2273, grad_fn=<MseLossBackward0>)
tensor(1.2343, grad_fn=<MseLossBackward0>)
tensor(1.2358, grad_fn=<MseLossBackward0>)
tensor(1.2329, grad_fn=<MseLossBackward0>)
tensor(1.2257, grad_fn=<MseLossBackward0>)
tensor(1.2059, grad_fn=<MseLossBackward0>)
tensor(1.2089, grad_fn=<MseLossBackward0>)
tensor(1.1991, grad_fn=<MseLossBackward0>)
tensor(1.2147, grad_fn=<MseLossBackward0>)
tensor(1.2029, grad_fn=<MseLossBackward0>)
tensor(1.2052, grad_fn=<MseLossBackward0>)
tensor(1.2056, grad_fn=<MseLossBackward0>)
tensor(1.21

In [46]:

sample1  = torch.randn( 1, 784 )
print( sample1.shape )

res1 = model( sample1 )
print(res1.shape)

pairwise_euclidean_distance( sample1, res1)


torch.Size([1, 784])
torch.Size([1, 784])


tensor([[28.9201]], grad_fn=<SqrtBackward0>)

In [47]:

sample2  = torch.randn( 1, 784 )
print( sample2.shape )

res2 = model( sample2 )
print(res2.shape)

pairwise_euclidean_distance( sample2, res2)


torch.Size([1, 784])
torch.Size([1, 784])


tensor([[29.1498]], grad_fn=<SqrtBackward0>)

In [48]:

sample3  = torch.randn( 1, 784 )
print( sample3.shape )

res3 = model( sample3 )
print(res3.shape)

pairwise_euclidean_distance( sample3, res3)


torch.Size([1, 784])
torch.Size([1, 784])


tensor([[28.5768]], grad_fn=<SqrtBackward0>)

In [35]:



x = torch.tensor([[0.9041, 0.0196]]  )

y = torch.tensor([[-2.1763, -0.4713]])

pairwise_euclidean_distance(x, y)


tensor([[3.1193]])