
## Mutual Information


In [5]:


from sklearn.feature_selection import mutual_info_classif
import numpy as np



## Example 1


In [6]:

##               f1,f2, f3,
X = np.array([   [1, 1, 0], 
                 [1, 0, 1], 
                 [1, 1, 1], 
                 [0, 1, 0], 
                 [0, 0, 1], 
                 [0, 1, 0],
                 [1, 0, 0]     ]
)  

X


array([[1, 1, 0],
       [1, 0, 1],
       [1, 1, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

In [7]:

y = np.array(
    [0, 
     1, 
     1, 
     0, 
     1, 
     0, 
     0]
)  

y


array([0, 1, 1, 0, 1, 0, 0])

In [11]:

mutual_info = mutual_info_classif(X, y, discrete_features=True)

mutual_info


array([0.01403222, 0.08878195, 0.6829081 ])

In [12]:

print("F1....", mutual_info[0] )
print("F2....", mutual_info[1] )
print("F3....", mutual_info[2] )


F1.... 0.014032215111297097
F2.... 0.0887819499348041
F3.... 0.6829081047004715



## Example 2


In [16]:

##               f1,f2, f3,
X2 = np.array([  [1, 1, 0], 
                 [1, 0, 1], 
                 [1, 1, 1], 
                 [0, 1, 0], 
                 [1, 0, 1], 
                 [0, 1, 0],
                 [0, 0, 0]     ]
)  

X2



array([[1, 1, 0],
       [1, 0, 1],
       [1, 1, 1],
       [0, 1, 0],
       [1, 0, 1],
       [0, 1, 0],
       [0, 0, 0]])

In [17]:

y = np.array(
    [0, 
     1, 
     1, 
     0, 
     1, 
     0, 
     0]
)  

y



array([0, 1, 1, 0, 1, 0, 0])

In [18]:

mutual_info = mutual_info_classif( X2, y, discrete_features=True )

mutual_info


array([0.36157374, 0.08878195, 0.6829081 ])

In [19]:

print("F1....", mutual_info[0] )
print("F2....", mutual_info[1] )
print("F3....", mutual_info[2] )


F1.... 0.36157373634686685
F2.... 0.0887819499348041
F3.... 0.6829081047004715
